services:
  client:
    build: ./client
    ports:
      - "3000:80"
    networks:
      - puppy-network

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PROJECT_URL
      - API_KEY
      - PORT
      - BUCKET_NAME
    networks:
      - puppy-network
    depends_on:
      - client

networks:
  puppy-network:
    driver: bridge
