apiVersion: v1
kind: Service
metadata:
  name: puppy-generator-server
spec:
  type: NodePort
  selector:
    app: puppy-generator-server
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30003
