apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppy-generator-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: puppy-generator-server
  template:
    metadata:
      labels:
        app: puppy-generator-server
    spec:
      containers:
      - name: puppy-generator-server
        image: wrwawra/puppy-generator:puppy-generator-server
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: DATABASE_URL
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: API_KEY
          - name: BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: BUCKET_NAME
      imagePullSecrets:
        - name: regcred
      
