apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppy-generator-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: puppy-generator-client
  template:
    metadata:
      labels:
        app: puppy-generator-client
    spec:
      containers:
      - name: puppy-generator-client
        image: wrwawra/puppy-generator:puppy-generator-client
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
