apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  API_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5seFptaHhjbVpxY25kM2EzRmxkVzFwWW5CeElpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTWprMU1UUTBOek1zSW1WNGNDSTZNakEwTlRBNU1EUTNNMzAuN2JTaUNFSnVfV3NqWmF0dlBNU0NRQ3JwYUhwRWxKX1lGRGhuenhpS1lwUQ==
  DATABASE_URL: aHR0cHM6Ly95cWZocXJmanJ3d2txZXVtaWJwcS5zdXBhYmFzZS5jbw==
  BUCKET_NAME: cHVwcGllcw==
